export { default as AccessibilityIcon } from "./AccessibilityIcon";
export { default as CorrectIcon } from "./CorrectIcon";
export { default as CSSIcon } from "./CSSIcon";
export { default as HTMLIcon } from "./HTMLIcon";
export { default as IconPlaceholder } from "./IconPlaceholder";
export { default as IncorrectIcon } from "./IncorrectIcon";
export { default as JSIcon } from "./JSIcon";
export { default as MoonIcon } from "./MoonIcon";
export { default as SunIcon } from "./SunIcon";
